<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[10]=array(0,1,1,'6L+Q6YCa5LiT5qCP');
$cfg_Cs[2]=array(0,1,1,'5ZWG5Lia56e75rCR');
$cfg_Cs[3]=array(0,1,1,'5oqA5pyv56e75rCR');
$cfg_Cs[4]=array(0,1,1,'6ZuH5Li75ouF5L+d');
$cfg_Cs[5]=array(0,1,1,'5r6z5rSy55WZ5a2m');
$cfg_Cs[6]=array(0,1,1,'5a625bqtL+WFtuWug+etvuivgQ==');
$cfg_Cs[7]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[8]=array(0,1,1,'5r6z5rSy6LWE6K6v');
$cfg_Cs[9]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'56e75rCR5paw6Ze7');
$cfg_Cs[12]=array(0,1,1,'5qGI5L6L54K56K+E');
$cfg_Cs[13]=array(0,1,0,'5Zyo57q/55WZ6KiA');
?>