
<field:name itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:mail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>

<field:sort itemname="咨询内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sort>

<field:content itemname="内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:content>
