<div class="post-2898 post type-post status-publish format-standard hentry category--">
                  <h3 class="news-title gap-f"> 
                  <a href="[field:arcurl/]">[field:title  function='( strlen("@me")>46 ? cn_substr("@me",26)."..." : "@me" ) ' /][field:textlink/]</a> 
                  <span>[field:pubdate function=MyDate('m-d',@me)/]    </span></h3>          
            </div>