<?php
$z[0]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",7591,7834);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("field","",7976,8005);
$z[1][4]['name']="position";
$z[2]=Array("list","\r\n    <li> [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); [/field:array]\r\n     [<b>[field:typelink/]</b>] <a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a> <span class=\"info\"> <small>日期：</small>[field:pubdate function=\"GetDateTimeMK(@me)\"/] <small>点击：</small>[field:click/] <small>好评：</small>[field:scores/] </span>\r\n     <p class=\"intro\"> [field:description/]... </p>\r\n    </li>\r\n    ",8082,8624);
$z[2][4]['pagesize']="10";
$z[3]=Array("pagelist","",8725,8803);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="5";

?>