<?php
$z[0]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",9644,9887);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:textlink/]</a> \r\n                  <span>[field:pubdate function=MyDate('m-d',@me)/]    </span></h3>          \r\n            </div> \r\n         ",13254,13701);
$z[1][4]['typeid']="1,,2,3,4";
$z[1][4]['row']="8";
$z[1][4]['titlelen']="40";
$z[1][4]['orderby']="pubdate";
$z[1][4]['limit']="0,8";
$z[2]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:textlink/]</a> \r\n                  <span>[field:pubdate function=MyDate('m-d',@me)/]    </span></h3>          \r\n            </div> \r\n         ",14040,14480);
$z[2][4]['typeid']="2";
$z[2][4]['row']="8";
$z[2][4]['titlelen']="40";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="0,8";
$z[3]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:textlink/]</a> \r\n                  <span>[field:pubdate function=MyDate('m-d',@me)/]    </span></h3>          \r\n            </div> \r\n         ",14868,15308);
$z[3][4]['typeid']="2";
$z[3][4]['row']="8";
$z[3][4]['titlelen']="40";
$z[3][4]['orderby']="pubdate";
$z[3][4]['limit']="0,8";

?>