<?php
$z[0]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",6677,6920);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:title function='( strlen(\"@me\")>43 ? cn_substr(\"@me\",44).\"...\" :\"@me\")' /]</a> \r\n                  <span>[field:pubdate runphp='yes']\r\n\$aa=strftime('%m-%d',@me);\r\n\$ntime = time();\r\n\$tagtime = @me;\r\n\$day3 = 3600 * 24 * 2;\r\nif(\$tagtime > \$ntime-\$day3) @me = \"\$aa.<img src='mon/wp-content/themes/1/images/new.gif'>\";\r\nelse @me = \$aa;\r\n[/field:pubdate]    </span></h3>          \r\n            </div> \r\n         ",22577,23282);
$z[1][4]['typeid']="10";
$z[1][4]['row']="8";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="pubdate";
$z[1][4]['limit']="0,7";
$z[2]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:title  function='( strlen(\"@me\")>35 ? cn_substr(\"@me\",35).\"...\" : \"@me\" ) ' /]</a> \r\n                  <span>[field:pubdate function=MyDate('m-d',@me)/]    </span></h3>          \r\n            </div> \r\n         ",23529,24046);
$z[2][4]['typeid']="1,10,2,3,4";
$z[2][4]['row']="7";
$z[2][4]['titlelen']="40";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="0,7";
$z[3]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:title function='( strlen(\"@me\")>43 ? cn_substr(\"@me\",43).\"...\" :\"@me\")' /]</a> \r\n                  <span>[field:pubdate runphp='yes']\r\n\$aa=strftime('%m-%d',@me);\r\n\$ntime = time();\r\n\$tagtime = @me;\r\n\$day3 = 3600 * 24 * 2;\r\nif(\$tagtime > \$ntime-\$day3) @me = \"\$aa.<img src='mon/wp-content/themes/1/images/new.gif'>\";\r\nelse @me = \$aa;\r\n[/field:pubdate]        </span></h3>          \r\n            </div> \r\n         ",24350,25059);
$z[3][4]['typeid']="11";
$z[3][4]['row']="7";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";
$z[3][4]['limit']="0,7";
$z[4]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:title function='( strlen(\"@me\")>43 ? cn_substr(\"@me\",43).\"...\" :\"@me\")' /]</a> \r\n                  <span>[field:pubdate runphp='yes']\r\n\$aa=strftime('%m-%d',@me);\r\n\$ntime = time();\r\n\$tagtime = @me;\r\n\$day3 = 3600 * 24 * 2;\r\nif(\$tagtime > \$ntime-\$day3) @me = \"\$aa.<img src='mon/wp-content/themes/1/images/new.gif'>\";\r\nelse @me = \$aa;\r\n[/field:pubdate]       </span></h3>          \r\n            </div> \r\n         ",25376,26084);
$z[4][4]['typeid']="12";
$z[4][4]['row']="8";
$z[4][4]['titlelen']="60";
$z[4][4]['orderby']="pubdate";
$z[4][4]['limit']="0,7";
$z[5]=Array("arclist","\r\n            <div class=\"post-2898 post type-post status-publish format-standard hentry category--\">\r\n                  <h3 class=\"news-title gap-f\"> \r\n                  <a href=\"[field:arcurl/]\">[field:title function='( strlen(\"@me\")>43 ? cn_substr(\"@me\",43).\"...\" :\"@me\")' /]</a> \r\n                  <span>[field:pubdate runphp='yes']\r\n\$aa=strftime('%m-%d',@me);\r\n\$ntime = time();\r\n\$tagtime = @me;\r\n\$day3 = 3600 * 24 * 2;\r\nif(\$tagtime > \$ntime-\$day3) @me = \"\$aa.<img src='mon/wp-content/themes/1/images/new.gif'>\";\r\nelse @me = \$aa;\r\n[/field:pubdate]        </span></h3>          \r\n            </div> \r\n         ",26459,27167);
$z[5][4]['typeid']="7";
$z[5][4]['row']="7";
$z[5][4]['titlelen']="60";
$z[5][4]['orderby']="pubdate";
$z[5][4]['limit']="0,7";

?>